# Generated by Django 4.2.11 on 2025-09-14 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField()),
                ('reviewer', models.CharField(max_length=250)),
                ('rating', models.ImageField(choices=[(1, 'Плохо'), (2, 'Неочень'), (3, 'Удовлетворительно'), (4, 'Хорошо'), (5, 'Отлично')], upload_to='')),
                ('is_published', models.BooleanField(default=False)),
                ('date_writing', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
