# Generated by Django 4.2.11 on 2025-09-14 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='rating',
            field=models.CharField(choices=[(1, 'Плохо'), (2, 'Неочень'), (3, 'Удовлетворительно'), (4, 'Хорошо'), (5, 'Отлично')], max_length=250),
        ),
    ]
