# Generated by Django 4.2 on 2025-08-01 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('weight', models.FloatField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('photo', models.ImageField(upload_to='menu/')),
                ('description', models.TextField(blank=True, null=True)),
                ('сomposition', models.TextField(blank=True, null=True)),
                ('rating', models.FloatField()),
                ('is_selling', models.BooleanField(default=False)),
            ],
        ),
    ]
